{{- if semverCompare ">=1.27.0" .Capabilities.KubeVersion.Version -}} 
# Create the service account token secret for the service account
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: '{{ template "workload-identity-webhook.name" . }}'
    azure-workload-identity.io/system: "true"
    chart: '{{ template "workload-identity-webhook.name" . }}'
    release: '{{ .Release.Name }}'
  name: azure-wi-webhook-admin-token
  namespace: '{{ .Release.Namespace }}'
  annotations:
    kubernetes.io/service-account.name: azure-wi-webhook-admin
type: kubernetes.io/service-account-token
{{ end }}
